### ISSUE TITLE
SIP REGISTER proxy

### ISSUE THREAD

**Issue by spointer** [drachtio/drachtio-srf#106]
I'm trying to send a register using an outbound proxy.

Does anyone know how I can do this? Is there any proxy something options to srf.request function?

**Comment by davehorton** [comment]
Yes, there is an `opts.proxy` property you can use on the srf.request function.

I see that is not documented, so I will update the documentation.

**Comment by spointer** [comment]
Thanks dave.
I checked drachtio-server sending to proxy server instead of request-URI.

**Comment by spointer** [comment]
BTW, does dialog.modify or dialog.request function has proxy options and is not documented?
I could see createUAC function of srf has opts.proxy but not in dialog functions.

**Comment by davehorton** [comment]
No, because a SipDialog already has a route established.....although, this is interesting and I don't know if I have tested it -- sending an invite with opts.proxy set and then seeing if re-invites are also sent through it.  You may want to test that

**Comment by spointer** [comment]
Actually, it seems re-invite message is directly sent to request-uri not to outbound proxy and why ack message is sent to request-uri?

192.168.10.135 ==> outbound proxy server(another drachtio)
sip.test.com(10.184.2.145) ==> target endpoint(request-uri)


`2021-04-30 21:22:52.465594 send 738 bytes to udp/[192.168.10.135]:5060 at 21:22:52.464396:
INVITE sip:2000@sip.test.com:5060 SIP/2.0
Via: SIP/2.0/UDP 172.26.0.2:5060;rport;branch=z9hG4bKp4UaNmSg2K5mH
Max-Forwards: 70
From: <sip:30000@172.26.0.2:5060>;tag=00y47Ueg9av1c
To: <sip:2000@sip.test.com:5060>
Call-ID: bd8104a0-a6da-40c2-8086-38222f19a11e
CSeq: 35338894 INVITE
Contact: <sip:30000@172.26.0.2:5060>
User-Agent: cogs-af9c5a1c-b1cf-4799-8668-282260a7c73b
Content-Type: application/sdp
Content-Length: 232
X-cogs-Version: callagent x.x.x

v=0
o=cogs 1619773422 1619773423 IN IP4 192.168.10.70
s=cogs
c=IN IP4 192.168.10.70
t=0 0
m=audio 12098 RTP/AVP 8 101
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-16
a=ptime:20
a=sendrecv 


2021-04-30 21:22:56.739764 recv 723 bytes from udp/[192.168.10.135]:5060 at 21:22:56.739494:
SIP/2.0 183 Session Progress
Via: SIP/2.0/UDP 172.26.0.2:5060;rport=59387;branch=z9hG4bKp4UaNmSg2K5mH;received=172.26.0.1
From: <sip:30000@172.26.0.2:5060>;tag=00y47Ueg9av1c
To: <sip:2000@sip.test.com:5060>;tag=c48ea9fc1c4f370a25ff7ac46d79ac9e
Call-ID: bd8104a0-a6da-40c2-8086-38222f19a11e
CSeq: 35338894 INVITE
Record-Route: <sip:10.184.2.145;lr>
Contact: <sip:2000@10.184.2.145:5060;user=phone;transport=UDP>
Content-Type: application/sdp
Content-Length: 225

v=0
o=aaa37757_55_ut4d98c068f08a 1619785373 1619785373 IN IP4 10.184.2.148
s=G3_12345
c=IN IP4 10.184.2.148
t=0 0
m=audio 20654 RTP/AVP 8 101
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000
a=ptime:20 


2021-04-30 21:22:59.367636 recv 709 bytes from udp/[192.168.10.135]:5060 at 21:22:59.367328:
SIP/2.0 200 OK
Via: SIP/2.0/UDP 172.26.0.2:5060;rport=59387;branch=z9hG4bKp4UaNmSg2K5mH;received=172.26.0.1
From: <sip:30000@172.26.0.2:5060>;tag=00y47Ueg9av1c
To: <sip:2000@sip.test.com:5060>;tag=c48ea9fc1c4f370a25ff7ac46d79ac9e
Record-Route: <sip:10.184.2.145;lr>
Call-ID: bd8104a0-a6da-40c2-8086-38222f19a11e
CSeq: 35338894 INVITE
Contact: <sip:2000@10.184.2.145:5060;user=phone;transport=UDP>
Content-Type: application/sdp
Content-Length: 225

v=0
o=aaa37757_55_ut4d98c068f08a 1619785373 1619785373 IN IP4 10.184.2.148
s=G3_12345
c=IN IP4 10.184.2.148
t=0 0
m=audio 20654 RTP/AVP 8 101
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000
a=ptime:20 


2021-04-30 21:22:59.407916 send 418 bytes to udp/[10.184.2.145]:5060 at 21:22:59.406092:
ACK sip:2000@10.184.2.145:5060;user=phone;transport=UDP SIP/2.0
Via: SIP/2.0/UDP 172.26.0.2:5060;rport;branch=z9hG4bKQDN3pFamZvU7c
Route: <sip:10.184.2.145;lr>
Max-Forwards: 70
From: <sip:30000@172.26.0.2:5060>;tag=00y47Ueg9av1c
To: <sip:2000@sip.test.com:5060>;tag=c48ea9fc1c4f370a25ff7ac46d79ac9e
Call-ID: bd8104a0-a6da-40c2-8086-38222f19a11e
CSeq: 35338894 ACK
Content-Length: 0


2021-04-30 21:22:59.482589 send 733 bytes to udp/[10.184.2.145]:5060 at 21:22:59.480024:
INVITE sip:2000@10.184.2.145:5060;user=phone;transport=UDP SIP/2.0
Via: SIP/2.0/UDP 172.26.0.2:5060;rport;branch=z9hG4bKSZ7mt5BUSe8cm
Route: <sip:10.184.2.145;lr>
Max-Forwards: 70
From: <sip:30000@172.26.0.2:5060>;tag=00y47Ueg9av1c
To: <sip:2000@sip.test.com:5060>;tag=c48ea9fc1c4f370a25ff7ac46d79ac9e
Call-ID: bd8104a0-a6da-40c2-8086-38222f19a11e
CSeq: 35338895 INVITE
Contact: <sip:30000@172.26.0.2:5060>
Content-Type: application/sdp
Content-Length: 232

v=0
o=cogs 1619773422 1619773423 IN IP4 192.168.10.70
s=cogs
c=IN IP4 192.168.10.70
t=0 0
m=audio 12098 RTP/AVP 8 101
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-16
a=ptime:20
a=sendrecv `

**Comment by spointer** [comment]
Hi Dave.
Any suggestions or updates on this?

**Comment by davehorton** [comment]
Actually, the proper way to force all requests through an outbound proxy is not in your app, but in the drachtio server config

https://drachtio.org/docs/drachtio-server#outbound-proxy

On May 4, 2021, at 12:34 AM, spointer ***@***.***> wrote:


Hi Dave.
Any suggestions or updates on this?
