### ISSUE TITLE
Is it possible to get "tag" value of To Header of 200 OK event when it is generated in response to SUBSCRIBE

### ISSUE THREAD

**Issue by p-akshay** [drachtio/drachtio-srf#109]
Hi All,

When a SUBSCRIBE event is responded with 200 OK, a "tag" parameter is associated with To Header.
Typically when we associate a NOTIFY for this subscribe the tag value is also required.

Can we get this from either req/res objects that srf uses? 

Explanation with logs:
```
SUBSCRIBE sip:test-server@***.org SIP/2.0
Via: SIP/2.0/UDP 192.*.0.*:50856;branch=z9hG4bK-1523174754;rport
From: <sip:444.mcla@ims.mnc001.mcc001.3gppnetwork.org>;tag=1966413601
To: <sip:test-server@***.org>
Call-ID: 9d4d0c1b-cd9d-e1d9-2744-cbc91172b7ca
```

This is incoming subscribe request...
the tag value present in From can be obtained using "req.getParsedHeader('From').params.tag"

Now following is the 200 OK response event generated

```
SIP/2.0 200 OK
Via: SIP/2.0/UDP 192.*.0.*:51591;branch=z9hG4bK-566995704;rport=51591
From: <sip:444.mcla@ims.mnc001.mcc001.3gppnetwork.org>;tag=1966413601
To: <sip:test-server@***.org>;tag=mtFZt13cU1Urc
Call-ID: 9d4d0c1b-cd9d-e1d9-2744-cbc91172b7ca
CSeq: 359918230 SUBSCRIBE
Contact: <sip:192.*.0.*:7318>
Content-Length: 0
```

Now I want to obtain Tag value in the To header (i.e. **tag=mtFZt13cU1Urc**) 
Use of "req.getParsedHeader('To').params.tag" and  of "res.getParsedHeader('To').params.tag" prints  "undefined" 

Any suggestions?

**Comment by davehorton** [comment]
hmm can you log `JSON.stringify(res.getParsedHeader('To'))`

**Comment by p-akshay** [comment]
It is like this 

```
{ name: undefined,
  uri: 'sip:test-server@***.org',
  params: {} }
```

**Comment by p-akshay** [comment]
One other issue w.r.t. this thread is "To" Address generated in SIP NOTIFY while using srf.request() method...

for example I have a client registered on my node server as test-111...the SIP username for this is sip:test-111@example.com and it's contact is "sip:test-111@192.1680.*.*:50788;transport=ws"

Now if I want to send a SIP Notify to this client I must use the contact header in srf.req and not the sip username

```
srf.request('sip:test-111@192.168.*.*:50788;transport=ws', {
    method: 'NOTIFY',
   body : "test Body"
}
```
The above code will generate the Notify  as expected ...
However, the To header in this case is "To : sip:test-111@192.168.*.*:50788;transport=ws"

If on the other hand I do following:

```
srf.request('sip:test-111@example.com', {
    method: 'NOTIFY',
   body : "test Body"
}
```

Then the SIP NOTIFY is not sent from drachtio server at all...
It returns DNS error (understandable as example.com is not resolvable in my environment)

But the problem here is then that To header of my NOTIFY will always have an IP Address component to it while doing testing (which is not the right option I think)...

Can we achieve the NOTIFY with custom to header while using the Contact Header string find the client endpoint ?

**Comment by davehorton** [comment]
In answer to your last question, you should be able to provide a To header to override the one generated from the URI.  Test this and let me know if it works
```
srf.request('sip:test-111@192.168.*.*:50788;transport=ws', {
    method: 'NOTIFY',
   headers: {To: 'sip:test-111@example.com',
   body : "test Body"
}
```

Now, as far as the original issue, it looks like a bug in drachtio-srf.  I will look into this within the next week or so

**Comment by p-akshay** [comment]
Hi @davehorton ,

Thank you for clarifying the issue w.r.t. To Header....

I have tried it and it works...

I also found out the workaround for my original issue...

Here is what I have done:

```
var tagB = 'abc123';  // Any Random String
var to = 'sip:test-111@example.com;tag=' + tagB;

const headers = {}
headers['To'] = to;

// Send 200 OK
res.send(200, { headers });

// Send Notify
srf.request('sip:test-111@192.168.*.*:50788;transport=ws', {
    method: 'NOTIFY',
   headers: headers,
   body : "test Body"
}

```
