### ISSUE TITLE
opts.proxy configuration affects the dialog routeset

### ISSUE THREAD

**Issue by amay1980** [drachtio/drachtio-srf#114]
Hi,
when I set the proxy configuration in a B2BUA using opts.proxy, I found out that the messages within a dialog initiated by an INVITE transaction (eg. ACK , BYE)  are routed to the URI configured in the opts.proxy rather than to the remote URI as set by the contact header received in the 200OK to the INVITE.

I think this is wrong and renders strange behaviours. According to 3261, the in-dialog requests should be routed based on the dialog routeset and ultimately based on the remote-URI. And the dialog routeset is built based on the record-route header.

What I saw is that , at least when there is no record-routing proxy in the way of the call, the UAC part of the B2BUA will still try to route towards opts.proxy instead than directly to the remote-URI setup during the dialog

Regards

**Comment by davehorton** [comment]
I actually don't think the `opts.proxy` setting is the issue here.  More likely, drachtio server determined that the far end endpoint is behind a NAT and routed the ACK/BYE requests accordingly.  Can you supply a drachtio log file, at debug, showing a call with this issue?

**Comment by amay1980** [comment]
Thanks for the hint.
There is no NAT in my setup. All the elements are attached to the same network 192.168.0.0/24. I have looked at the logs at debug as suggested and I see the following:

2021-10-06 21:06:32.830512 SipDialogController::processResponse - (UAC) detected downstream client; contact ip: 192.168.0.6 differs from recv address: 192.168.0.7
2021-10-06 21:06:32.830694 SipDialogController::processResponse - (UAC) detected nat setting route to: sip:192.168.0.7:5060

The setup I have is: UA-A(.6) --->proxy(.7)--->drachtio-server (.8) (acting as B2BUA)-->proxy--->UA-B
It seems that drachtio-server realises that the contact header (UA-A address) does not coincide with the src address it receives (proxy address) and thus concludes that UA-A is behind NAT. So it is wrongly assuming that the SIP proxy is really a NAT. 

IMHO I think this is a wrong behaviour. I think NAT detection should be based on the Via not on the Contact (as there may be proxies in the middle). Also , I think that this type of implementation should be based on the outbound spec and applied when drachtio-server is acting as an edge proxy.

Would there be a way to deactivate this type of behaviour at config level?

Thanks!

**Comment by amay1980** [comment]
Thanks for the response.
About the NAT in the UAC leg:
- Let's assume  a setup (different from the one that I was testing) in which drachtio is acting as a SIP server directly facing the UA (eg. in the Internet). In that case, I'd agree, the UA's are very likely to be behind a NAT. However in those scenarios the UA's will need to register to the sip server and there are already standardised mechanisms to deal with the NAT issue in such cases without the need to make assumptions (eg. RFC5626). Many UAs out there do not fully support this so I acknowledge simplified outbound mechanisms might also need to be supported (like sending terminating requests to the flow created by the registration process).The way to know if there is a NAT or not here could be to compare the REGISTER's Via with src:port.

- If, on the other hand, we have an scenario (like the one in my setup) in which drachtio is acting as an App Server (in this case as a B2BUA) I think there must be other elements that take care of the registration (registration/proxy) and other elements that may be facing the UAs (eg. edge proxies). Therefore in those scenarios drachtio would not need to bother about the NAT issue.

I understand the user needs to tell drachtio in which scenario it is (I think the conf switch is a good idea). My point is that ,in case NAT is assumed , the way to go would be to apply as much as possible standardised mechanisms (like RFC5626) or leverage the registration flow information.

The logic that you explain above on the UAS leg is , I guess , meant to overcome an scenario in which there is a NAT between the SIP server/proxy ,where users are registering, and drachtio. I think this would be a rather unusual scenario, in my experience.

Thanks
