### ISSUE TITLE
407 response with re-Invite

### ISSUE THREAD

**Issue by spointer** [drachtio/drachtio-srf#133]
Hello dave,

When my app sends re-INVITE with dialog.modify('hold') function, the remote server(actually Avaya SM) sends 407 proxy authentication required.
The problem is that it seems modify function has no auth option as the request function has.

Could you consider supporting auth option to the modify function like this?
dialog.modify('hold', {
    headers: {
        field: 'value'
    },
    auth: {
        username: 'test',
        password: 'password'
    }
}, function(err, res) {
});

Thank you.

**Comment by davehorton** [comment]
available in drachtio-srf@4.5.13
