### ISSUE TITLE
SipError: Sip non-success response: 408

### ISSUE THREAD

**Issue by paulgrammer** [drachtio/drachtio-srf#146]
I am experiencing difficulty establishing a SIP trunk connection with Drachtio. When attempting to make a call using the `srf.createB2BUA(req, res, "+256701964030@192.168.100.42")` function, it takes a considerable amount of time and eventually returns the error `SipError: Sip non-success response: 408`.

I have verified that the SIP trunk works flawlessly with other SIP clients. However, when using Drachtio, this issue consistently arises.

**Comment by davehorton** [comment]
a 408 is generated by the sip stack when it sends a request and the far end never responds, not even with a 100 Trying

**Comment by paulgrammer** [comment]
@davehorton  I'm still facing the issue where attempting to send a trunk invite to the SIP trunk '+256701964030@192.168.100.42' using the 'drachtio-srf' SIP client results in a failed connection. Surprisingly, when using other SIP clients, I can successfully establish a connection to the same address. I've been troubleshooting this problem for a week now, and I'm still unable to determine the root cause. I've thoroughly reviewed the documentation, which appears to be clear and comprehensive, but I'm at a loss as to what might be causing this behavior. Any insights into the possible causes of this issue would be greatly appreciated.

**Comment by davehorton** [comment]
please set drachtio loglevel to debug, try again, and post the drachtio log file here

**Comment by paulgrammer** [comment]
@davehorton Sorry I found out the issue was about my network, I'm running the server in docker and  at some what point docker wasn't allowing to access services on host machine. but I figured it out. Thank you for your concern on this issue
