### ISSUE TITLE
Public IP in Contact Header in #createUAS

### ISSUE THREAD

**Issue by sumit-kumar-iitm** [drachtio/drachtio-srf#155]
I am responding to the sip invite using the createUAS function but the contact header is picking the local IP of my instance. What change do I need to make to update it to the public IP of the instance? I am running drachtio-server and my client application in the same machine

**Comment by JSimoni42** [comment]
You could use the `external-ip` setting to achieve this. See the [contacts](https://drachtio.org/docs/drachtio-server#contacts) section of the configuration.

**Comment by davehorton** [comment]
@JSimoni42 is right, I would simply rephrase to say you **must** use external-ip if the public-ip is assigned over the top by your infrastructure (ie does not show up when you do `ifconfig`)
