### ISSUE TITLE
Middleware not executed for in-dialog requests

### ISSUE THREAD

**Issue by jonastelzio** [drachtio/drachtio-srf#64]
Right now it doesn't look like middleware (i.e. srf.use) is executed for in-dialog requests, such as reinvites.

That would be pretty useful, though I of course don't know if it's by design this isn't the case?

**Comment by davehorton** [comment]
Yes, someone else has mentioned that this would be useful.  I should probably add it.  Just for my edification, can you give me an example of how you would want to use it?

**Comment by jonastelzio** [comment]
Sure thing!

Right now I've got this middleware method (simplified for readability):
```
srf.use((req, res, next) => {
    if(req.source_address === kamailioIp)
    {
        info("Request received from Side A");
        req.isFromKamailio = true;
    }
    else {
        info("Request received from Side B");
    }
    
    next();
});
```

I later use req.isFromKamailio to determine on which side of drachtio the request originates from. In my handleRefer method I also need this information, but because indialog requests aren't pushed through this middleware, I need to repeat that same code in there to figure out if a reinvite originated from an Asterisk server or a WebRTC client - particularly useful when setting the right RtpEngine parameters ;)
